---
- hosts: all
  become: true

  tasks:
  
    - user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/bash
        uid: 1001
        groups: sudo
        append: yes
        
    - authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', public_key_file) }}"
        